### ISSUE TITLE
Request for VISA Model Weights

### ISSUE THREAD

**Issue by rxtan2** [cilinyan/VISA#6]
Hi,

Thank you very much for this exciting work! Can you please share the link to the model weights?

**Comment by cilinyan** [comment]
Due to the large number of experiments, I'm not certain if the following checkpoint (VISA-7b) corresponds to the metrics reported in our paper. I will make time soon to locate the correct checkpoint and release it. 

Download Link: [OneDrive](https://mailsjlueducn-my.sharepoint.com/:u:/g/personal/yancl9918_mails_jlu_edu_cn/EaKhU3qHGvpDpLJlo0nmWfQBwlKrXxyTc_jDWlhD9g0YNQ?e=a2Ewnr), [BaiduPan](https://pan.baidu.com/s/1lO1B7RwXLy_wQrJ5w3Dc1w?pwd=visa)

**Comment by SU-470** [comment]
I use the weights of VISA-7b for validation, but I got the poor results:”
{
    "referring": {
        "J": 9.72982428115016,
        "F": 17.145779552715656,
        "A": 84.83459744408947,
        "R": 12.401632587859424,
        "JF": 13.437801916932909
    },
    "reason": {
        "J": 8.21130505050505,
        "F": 15.329995959595959,
        "A": 85.16438383838383,
        "R": 13.39201616161616,
        "JF": 11.770650505050504
    },
    "overall": {
        "J": 8.970564665827606,
        "F": 16.237887756155807,
        "A": 84.99949064123665,
        "R": 12.896824374737793,
        "JF": 12.604226210991706
    }
}“,It is worth noting that my torch and transform versions are relatively new. Do you know what the reason is?

**Comment by SU-470** [comment]
> Hi,
> 
> Thank you very much for this exciting work! Can you please share the link to the model weights?

Have you ever tested the official model? What's the result?
